<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>nectarefa</name>
  <version>0.0.0</version>
  <description>Autonomous drone mission using YASMIN state machines and Nectar SDK</description>
  <maintainer email="arthuraxribeiro@gmail.com">arthur-xavier</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>nectar</depend>
  <depend>nectar_interfaces</depend>

  <exec_depend>yasmin</exec_depend>
  <exec_depend>yasmin_ros</exec_depend>
  <exec_depend>yasmin_viewer</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
